### your site title here

title: blijblijblij.com
url: "https://blijblijblij.com"
description: "Recent content on blijblijblij.com"
baseurl: ""
email: blijblijblij@hey.com
twitter: https://www.twitter.com/blijblijblij
github: https://github.com/blijblijblij
instagram: https://www.instagram.com/blijblijblij/

feed:
  path: index.xml
  posts_limit: 10

highlighter: rouge
markdown: kramdown
paginate: 8

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
