name: Build and Deploy to Github Pages

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      -  task/Fuck-hugo-move-to-jekyll 
      # master  # Here source code branch is `master`, it could be other branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
