name: Test and Deploy

on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7]
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build to _site
        run: |
          jekyll build -d _site

  build_and_deploy:
    # run only on master branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/task/Fuck-hugo-move-to-jekyll'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages
          FOLDER: _site
